language: python

python:
    - "2.7"

before_install:
    - "sudo apt-get update"
    - "sudo apt-get install python-dev"

install:
    - "pip install -r requirements.txt > /dev/null"

before_script:
    - "python -m spacy.en.download all > /dev/null || echo 'SpaCy install failed'"

script:
    - "cd training"
    - "python trainer.py -uoc"
    - "cd ../app"
    - "cat test_input_file | python app.py --test > test_output_file"
    - "diff correct_output_file test_output_file"
